#ifndef CONFIG_H_
#define CONFIG_H_

//PENGATURAN SERIAL
#define BAUD 115200

//PILIHAN BOARD MCU UNTUK ROBOT
#define BOARD_CHOICE MEGA2560
#define MEGA2560    0 //ARDUINO MEGA2560

//PANJANG LENGAN ROBOT
#define SHANK_LENGTH 140.0
#define LOW_SHANK_LENGTH 140.0
#define HIGH_SHANK_LENGTH 140.0

#define END_EFFECTOR_OFFSET 77.0// PANJANG DARI BEARING LENGAN ATAS KE TENGAH END EFFECTOR DALAM MM

//PENGATURAN INTERPOLASI AWAL
//  INITIAL_XYZ MEMBENTUK LENGAN BAWAH VERTIKAL & LENGAN ATAS HORIZONTAL PADA 90 DERAJAT
#define INITIAL_X 0.0 // KOORDINAT KARTESIUS X  
#define INITIAL_Y (HIGH_SHANK_LENGTH+END_EFFECTOR_OFFSET) // KOORDINAT KARTESIUS Y
#define INITIAL_Z 138.0 //LOW_SHANK_LENGTH // KOORDINAT KARTESIUS Z

#define INITIAL_E0 0.0 // POSISI ENDSTOP STEPPER REL 

//  KALIBRASI STEP HOME UNTUK MENCAPAI POSISI INITIAL_XYZ YANG DIINGINKAN
#define X_HOME_STEPS 900  //STEP DARI X_ENDSTOP KE INITIAL_XYZ UNTUK LENGAN ATAS (Z)
#define Y_HOME_STEPS 800  //STEP DARI Y_ENDSTOP KE INITIAL_XYZ UNTUK LENGAN BAWAH (Y)
#define Z_HOME_STEPS 3520 // STEP DARI Z_ENDSTOP KE INITIAL_XYZ UNTUK PUSAT ROTASI (X)
#define E0_HOME_STEPS 200 // STEP DARI E0_ENDSTOP KE INITIAL_E0

//PENGATURAN HOMING:
#define HOME_X_STEPPER true // "true" JIKA ENDSTOP TERPASANG
#define HOME_Y_STEPPER true // "true" JIKA ENDSTOP TERPASANG
#define HOME_Z_STEPPER true // "true" JIKA ENDSTOP TERPASANG
#define HOME_E0_STEPPER true // "true" JIKA ENDSTOP TERPASANG
#define HOME_ON_BOOT false // "true" JIKA PERLU HOMING SETELAH POWER ON
#define HOME_DWELL 1200 // TAMBAH NILAI UNTUK MEMPERLAMBAT KECEPATAN HOMING

//PENGATURAN STEPPER:
#define MICROSTEPS 16 // KONFIGURASI MICROSTEPPING PADA RAMPS1.4
#define STEPS_PER_REV 200 // STEP PER PUTARAN UNTUK NEMA17
#define INVERSE_X_STEPPER true // UBAH JIKA STEPPER BERGERAK TERBALIK
#define INVERSE_Y_STEPPER false // UBAH JIKA STEPPER BERGERAK TERBALIK
#define INVERSE_Z_STEPPER true // UBAH JIKA STEPPER BERGERAK TERBALIK
#define INVERSE_E0_STEPPER true // UBAH JIKA STEPPER BERGERAK TERBALIK

//PENGATURAN REL: (microsteps 8)
#define RAIL true // Set nilai ke "true" jika menggunakan rel, set ke "false" jika robot tidak pakai rel.
#define STEPS_PER_MM_RAIL 80.0 // STEP PER MM UNTUK MOTOR REL
        //RUMUS: STEPS_PER_REV * MICROSTEPS / MOTOR_GEAR_TEETH / 2 
#define RAIL_LENGTH 355.0 // PANJANG MAKSIMAL REL DALAM MM

//PENGATURAN ENDSTOP:
#define X_MIN_INPUT 0 // NILAI OUTPUT SAAT SWITCH AKTIF - NO: 0, NC: 1
#define Y_MIN_INPUT 0 // NILAI OUTPUT SAAT SWITCH AKTIF - NO: 0, NC: 1
#define Z_MIN_INPUT 0 // NILAI OUTPUT SAAT SWITCH AKTIF - NO: 0, NC: 1
#define E0_MIN_INPUT 0 // NILAI OUTPUT SAAT SWITCH AKTIF - NO: 0, NC: 1

//PENGATURAN RASIO GERIGI
#define MOTOR_GEAR_TEETH 20.0 // 20.0 UNTUK VERSI BELT 20SFFACTORY   9.0 UNTUK VERSI GERIGI FTOBLER
#define MAIN_GEAR_TEETH 90.0 // 90.0 UNTUK VERSI BELT 20SFFACTORY   32.0 UNTUK VERSI GERIGI FTOBLER

//PENGATURAN PERALATAN
#define VACUM_DELAY_ON 300 // DURASI VACUM ON SEBELUM BERGERAK LAGI
#define VACUM_DELAY_OFF 300 // DURASI VACUM OFF SEBELUM BERGERAK LAGI
#define FAN_DELAY 1000 // DURASI FAN MENYALA DALAM DETIK

#define MAX_SERVO 115
#define MIN_SERVO 27

//PENGATURAN ANTRIAN PERINTAH
#define QUEUE_SIZE 15

//PENGATURAN BALASAN CETAK
#define PRINT_REPLY true // "true" UNTUK MENCETAK PESAN SETELAH SATU PERINTAH DIPROSES
#define PRINT_REPLY_MSG "ok" // PESAN YANG DIKIRIM UNTUK PEMROSESAN LANJUT DENGAN SOFTWARE LAIN

//PENGATURAN PROFIL KECEPATAN DEFAULT 
#define SPEED_PROFILE 2 // PILIHAN DIBAWAH
//0: KURVA KECEPATAN DATAR (KECEPATAN KONSTAN PER GERAKAN, COCOK UNTUK SOFTWARE KONTROL REAL-TIME)
//1: APROKSIMASI ARCTAN (AKSELERASI & DESELERASI KURVA LONCENG RINGAN)
//2: APROKSIMASI COSIN (AKSELERASI PENUH DARI 0 & DESELERASI KE 0, COCOK UNTUK GERAKAN PERINTAH PRESET)

//PENGATURAN LOG
#define LOG_LEVEL 2
//0: ERROR
//1: INFO
//2: DEBUG

//PARAMETER BATAS GERAK
#define Z_MIN -140.0 //TINGGI Z MINIMUM UJUNG TOOL MENYENTUH LANTAI
#define Z_MAX (LOW_SHANK_LENGTH+70.0) //PANJANG SHANK DITAMBAH ANGKA ACAK UNTUK Z_MAX
#define SHANKS_MIN_ANGLE_COS 0.791436948 
#define SHANKS_MAX_ANGLE_COS -0.774944489 
#define R_MIN (sqrt((sq(LOW_SHANK_LENGTH) + sq(HIGH_SHANK_LENGTH)) - (2*LOW_SHANK_LENGTH*HIGH_SHANK_LENGTH*SHANKS_MIN_ANGLE_COS) ))
#define R_MAX (sqrt((sq(LOW_SHANK_LENGTH) + sq(HIGH_SHANK_LENGTH)) - (2*LOW_SHANK_LENGTH*HIGH_SHANK_LENGTH*SHANKS_MAX_ANGLE_COS) ))

#endif
